spring:
  application:
    name: my-gateway
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9004
server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://@localhost:7001/eureka/
zuul:
  routes:
    detail-c: /user/**

logging:
  level: info